name: CD-staging

on:
  push:
    branches:
      - release

jobs:
  build-staging-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./staging" --public-url "./"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./staging"

  deploy-staging-job:
    needs: build-staging-job
    environment: "staging-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
